spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

stripe.secret=${STRIPE_SECRET}
security.jwt.secret=${JWT_SECRET}

spring.data.redis.port=${REDISPORT:6379}
spring.data.redis.host=${REDISHOST}
spring.data.redis.username=${REDISUSER}
spring.data.redis.password=${REDISPASSWORD}
spring.redis.client.type=jedis
spring.data.redis.database=0

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}
